### ISSUE TITLE
Amend: format deadline date 

### ISSUE THREAD

**Issue by tessav** [CS2103AUG2016-F10-C3/main#34]

**Comment by tessav** [comment]
check out libraries

**Comment by ravishwetha** [comment]
suggested by @shaocloud: Natty

**Comment by ravishwetha** [comment]
I've been trying to add natty for the good part of the day now embarrassingly and I just can't seem to get it to import despite adding the jar file in many ways as suggested online. I was able to import pretty time but not pretty time nlp which is more useful to us. @shaocloud could you take a look at this since you were working on the start and end date earlier, I'll look into doing one of your issues.

**Comment by ravishwetha** [comment]
It's ok, I got it to work! C3/feature/date-parsing with some Unit errors due to un-updated tests. Using Natty

**Comment by tessav** [comment]
tests passed so i've merged to base
