### ISSUE TITLE
Feature: Bring up Google Maps when selecting Task

### ISSUE THREAD

**Issue by shaocloud** [CS2103AUG2016-F10-C3/main#40]
A Google search isn't useful enough!

**Comment by ravishwetha** [comment]
I think that a calendar API should be the default and that maps could be an enhancement since our application is time based more so than location (To Do App vs Addressbook). 

The main problem I have with my GTD (apple reminders on iPhone) is that I have to switch between that and my calendar. It is possible to only use the calendar only but I like the priority rank and simple list UI (instead of searching for the date boxes with dots on them) of the reminders app. It is possible to use the reminders app only as it does show the date wheel but it is a pain to spin it if I want to set a task in the far future. I only occasionally use the google maps app for the small portion of location based tasks that don't tend to be completed at my desk so while that would be a really cool thing to have (possibly as a tab pane with the calendar).

GMaps : http://rterp.github.io/GMapsFX/
Calendar : https://dzone.com/articles/javafx-script-calendar-display
Tab Pane : https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/TabPane.html

**Comment by ravishwetha** [comment]
Hey, I was able to make it search google maps for the address of the task, but it only took one line to change so I'm going to add that commit directly to master. all the test cases are passing because there weren't specific ones for what the browser searched.

If we want to enhance this like extracting the travel time using current user location and task location then we can start a new issue.
